Update the codebase

diff --git a/.github/workflows/terraform-validate.yml b/.github/workflows/terraform-validate.yml
--- a/.github/workflows/terraform-validate.yml
+++ b/.github/workflows/terraform-validate.yml
@@ -51,3 +51,11 @@ jobs:
           exit 1
         fi
         echo "outputs.tf is present."
+    
+    - name: Check tfplan
+      run: |
+        if [ ! -f tfplan ]; then
+          echo "tfplan file not found!"
+          exit 1
+        fi
+        echo "tfplan file is present."
